version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  stock_checker-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stocks_db
    ports:
      - "5432:5432"

  producer:
    build: ./producer
    depends_on:
      - kafka
    environment:
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: stock_prices
      STOCK_SYMBOLS: "AAPL,MSFT,GOOGL,AMZN,NVDA,TSLA"

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - stock_checker-postgres
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: stock_prices
      POSTGRES_URI: postgresql+psycopg2://postgres:root@stock_checker-postgres:5432/stocks_db
